### PR TITLE
generic github actions 

### PR DESCRIPTION
**Pull request by jonapich**
Welcome to coveooss/coveo-python-oss!

I have many goals with this repository, but in a nutshell, I want to centralize Coveo's Python efforts in one place to promote reuse between teams.

I already pushed a number of libraries that you can browse. A lot of it is used in the core repository.

This PR is about the github actions. I have more or less reproduced what our Jenkins used to do. In this example I demonstrate how to test a project using pyproject ci (it does mypy, pytest, etc and we can extend it) and how it can be pushed to pypi.org when changes are detected, with automatic versioning.

I hope you'll find this interesting and will be willing to collaborate and move your most useful python bits in here so everyone can benefit from them!

Also: Should I move coveo-pyproject and coveo-pypi-cli into their own repository since they're really apps and not libs? Or do you think it's kinda sexy to have everything in one repository, for instance so we can manage a virtual environment that always contains all of the libraries, for development convenience?

### CODE REVIEW

**Comment by jfsmith-at-coveo** [comment]
This looks like a nice and much needed initiative but before going further I'm unclear on where exactly this project comes in with the "python at Coveo" situation, because a few things I'm seeing do not seem to fit well with the description of the PR. I have a bunch of questions that mostly all fall under the same topic:

- Are we really planning to open-source some of our python code?
- Is this project meant to be useful internally?
- Should/can we support our internal pypi?

**Comment by jonapich** [comment]
> * Should/can we support our internal pypi?
The goal is to get rid of it, in my case. I already have the code that supports private repos, I just did not add it here. If we moved the publish-to-pypi action to, say, `coveo/actions` repo, then I would allow private repos to be configured.

So the history bit is that our internal pypi.dev server randomly fails our 45min+ runs when it feels like it. Then, github actions are really fun, and I'm personally sick of wasting my time with jenkinsfiles. I don't see the advantage of our internal pypi server if nothing in the code is actually secret or coveo-specific, and since we don't have self-hosted runners yet... here we are!

> * Are we really planning to open-source some of our python code?
Are there any reasons not to? This sounded like a bad critic :P

> * Is this project meant to be useful internally?
It's been an important part of the core repository for a while. Some of the modules were also key parts of elasticsearch-service and the coredump detector uses some of those libs as well. I am hoping that the internal use will become the de-facto "how to build a python project if you want everything to magically work for you and coveo" just like the deployment pipeline offered a way for all teams to manage their infrastructure the same way.

**Comment by jfsmith-at-coveo** [comment]
> The goal is to get rid of it, in my case. I already have the code that supports private repos, I just did not add it here. If we moved the publish-to-pypi action to, say, `coveo/actions` repo, then I would allow private repos to be configured.
> So the history bit is that our internal pypi.dev server randomly fails our 45min+ runs when it feels like it. Then, github actions are really fun, and I'm personally sick of wasting my time with jenkinsfiles. I don't see the advantage of our internal pypi server if nothing in the code is actually secret or coveo-specific, and since we don't have self-hosted runners yet... here we are!

It's funny because I too have been thinking for a long time about getting rid of the pypi dependency. It sucks that it breaks your builds. In my case it never happens because I pull from pypi when I build a docker image and then never again. Since you can pip-install from a url, my idea has been to simply add the distribution builds as downloadable files in github and voilà. Not sure about authentication and all that, but just to say, my thinking goes in the same direction.

I see no compelling reason to push our internal code to the outside world's pypi, but about that, see my next paragraph.

> Are there any reasons not to? This sounded like a bad critic :P

LOL! Sorry for the misunderstanding. The "are we really" meant something like "woah things are going faster here than I expected have I missed a memo or something".

Open-sourcing code to non-Coveo outsiders is one hell of a big move. We need to discuss and agree on a LOT of things beforehand, without even going into the licensing issues. I'm fairly convinced the JS UI team didn't do it in one day. This is not a cakewalk.

> I am hoping that the internal use will become the de-facto

I'm all for that, but I don't think an internal "Coveo Python SDK" is the same project as opening up our code to the wilderness, or that they can started at the same time.

Just my two cents!

**Comment by jonapich** [comment]
> Since you can pip-install from a url, my idea has been to simply add the distribution builds as downloadable files in github and voilà. Not sure about authentication and all that, but just to say, my thinking goes in the same direction.

Is that different from using the git+ syntax from pip? Can you use dependency managers and resolve dependency constraints using that approach?

> Open-sourcing code to non-Coveo outsiders is one hell of a big move. We need to discuss and agree on a LOT of things beforehand, without even going into the licensing issues. I'm fairly convinced the JS UI team didn't do it in one day. This is not a cakewalk.

This is how I see this: if it generates interest and activity outside coveo, it means it was a good idea _and_ it puts the coveo brand somewhere else in the software world, and that's only a good thing. If no one cares, then we still have the advantage of a convenient solution that requires less overhead (and that is probably more stable) than having our private pypi server.

I'll open up a chat in slack so we can discuss. Licensing and Documentation is one of the topics I wanted to bring up. User/project adoption is important too and I was thinking maybe you guys had projects that would be worth sharing. Release model, I already have a lot in place but it's not set in stone (hence the review request); it's just how I'm used to do things.

**Comment by jfsmith-at-coveo** [comment]
> Is that different from using the git+ syntax from pip? Can you use dependency managers and resolve dependency constraints using that approach?

No idea here. Can dependency managers support the same formats that you can use in a Requirements file? You know I'm still living in the Stone Age here. :sweat: But all I know is that our internal packages in a req file can be specified directly with an URL instead of relying on a pypi index. The auth part stumps me, but the VCS syntax (instead of http) might be the solution.

**Comment by jonapich** [comment]
> > Is that different from using the git+ syntax from pip? Can you use dependency managers and resolve dependency constraints using that approach?
> 
> No idea here. Can dependency managers support the same formats that you can use in a Requirements file? You know I'm still living in the Stone Age here. 😓 But all I know is that our internal packages in a req file can be specified directly with an URL instead of relying on a pypi index. The auth part stumps me, but the VCS syntax (instead of http) might be the solution.

The VCS solution requires a working VCS client, so in that sense I prefer the http solution. Both solutions may only point to 1 "version"; otherwise said, without a pypi index, others are forced to depend on that exact version and won't receive updates unless they change the url. You could fake a "latest" by providing a version-less URL (much like pointing to the main branch when using the git approach) and update it as you release, but that's an even greater problem 🤣 

coveo-pyproject can store your project and all its dependencies in a folder. You could probably zip that, and upload to github to create releases that you can download and install offline using the pip+url method!

**Comment by jfsmith-at-coveo** [comment]
> Both solutions may only point to 1 "version"

Indeed, I hadn't thought of that. This would work for my own needs but I admit that it cannot be the main solution. Drat!

**Comment by jonapich** [comment]
Every other PR was approved, this one is like a huge blob of them all so that the initial submission is solid. I am kicking this off.

**Pull request merged**
