### PR TITLE
Formatted with black

### PR DESCRIPTION
**Pull request by jonapich**
This is the black-formatted version. The CI check and auto-fixer is coming soon.

### CODE REVIEW

**Comment by dblanchette** [comment]
I'm sorry if I've missed it, but did you configure a line length? I'm not very comfortable with the default of 80. In our projects we add the following to `pyproject.toml`:
```
[tool.black]
line-length = 120
```
I see lines of 120 columns, so I figure it's what you're using too.

Also, is there/will there be a check in CI to make sure no commit comes without black format? It is annoying for the next person to modify the code to have unrelated changes.

**Review by dblanchette — APPROVED** [review]

**Comment by jfsmith-at-coveo** [comment]
I'm expecting death stares and tomatoes thrown my way, but if we build something for everyone, shouldn't we agree on conventions first?

Because if this repo has 120 by default, it will set the wrong example in my opinion. My apologies for such a hard stance, but 100 is not only a good compromise, it's the actual PEP8 recommandation! Black's default of 80 not particularly justifiable. 

I think that for something "coveo-wide" that might be open-sourced one day, we need to do one of two things:

1) Stick as much as possible to PEP documents and known conventions, regardless of what we do in our respective team's code base
2) Come up with Coveo's own python convention that we document clearly and exemplify with the content of coveo-python-oss

I think that #2 is something Coveo has been lacking for a long time. Like our own little PEP or something like that? This repo seems to be the place to start talking about it. I really want us all to be invested in this. Oh and though I'm ready to compromise on a lot of things outside my comfort zone (as we all should), that 120 thing absolutely needs a discussion first. ;-)

**Comment by jonapich** [comment]
@jfsmith I can change it to 100. I'm all in for following existing conventions, especially PEPs, since they're the easiest to argue and justify whenever the need arise.

**Comment by jonapich** [comment]
The checks are running in https://github.com/coveooss/coveo-python-oss/pull/9 with a 100 line length

**Comment by dblanchette** [comment]
> 100 is not only a good compromise, it's the actual PEP8 recommandation!
Where do you see this? Looking at the PEP-8, I still see 79. For us, 120 was already a compromise between 79 (PEP-8) and 150 (our previous standard).

In our experience it is a comfortable sweet spot. Shorter limits discourage having descriptive variable names. Longer limit is uncomfortable to read side-by-side. Another drawback of a small limit is that PRs seems longer than they are.

**Comment by jfsmith-at-coveo** [comment]
It's in the Maximum Line Length section:

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters.

I remembered 100 but 99 == 100, as we all know. :sweat_smile: In my pycharm I display line rulers at 100 and 72.

I think they amended the original PEP8 without really changing the base rule because of the standard library conventions that they want to keep at 80. They also specifically state this in the next paragraph.

When we read between the lines, it's pretty clear that this paragraph is an admission that 100 is reasonable for all newer python projects of our own.

**Comment by dblanchette** [comment]
Anyway, I can live with 100, especially with black doing the formatting for us.

**Comment by jfsmith-at-coveo** [comment]
> Anyway, I can live with 100, especially with black doing the formatting for us.

I didn't know about the 150 standard, which sounds scary. :cold_sweat: So I do understand how far there is to go from there to lower lengths! :bow: 

To my mind, it's rather easy to change one's own habits and conventions when we start a new project. That's how I have been able to start using typing annotations, for example. It's better to start with a blank page rather than look at existing code and feel all the despair of refactoring everything. That's why I thought this repo was the right place to use the more common value.

**Review by klalumiere — APPROVED** [review]
I agree with JF to go with PEP8 (100), especially since, as far as I know, this repository is already open sourced!

For side by side work, on my rescaled (150%) 4K:

image

**Comment by jonapich** [comment]
> For side by side work, on my rescaled (150%) 4K:

Lol! 150%?

Here's my 4k, 100% (yes, that's how I work)

image

**Review by jfsmith-at-coveo — APPROVED** [review]

**Pull request merged**
